spring.application.name=practice

jwt.key=${SECRET_KEY}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

